### ISSUE TITLE
Update.

### ISSUE THREAD

**Issue by geertjanknapen1** [geertjanknapen1/blog-laravel#1]
@NiemandNatural  I added you as a collaborator on this project. Feel free to re-use anything/clone the repo to your local system.
Also added you as a contributor to my planning board. I only gave you read permissions instead of write since I might need that board for a later project and I don't want it jumbled up.

**Comment by NiemandNatural** [comment]
That's okay, I just wanted to be able to see the code to have a reference. I won't touch anything. Thanks!

**Comment by geertjanknapen1** [comment]
@NiemandNatural Oh no you can break this repo, I don't care. (You won't be able to break it without a PR due to the rules I set up, so I have to review).

I just don't want to mess with the project :)
